### PR TITLE
wireguard-tools: update to 20180202 and add patch for 64bit arches

### PR DESCRIPTION
**Pull request by Grimler91**

### CODE REVIEW

**Comment by stephengroat** [comment]
@Grimler91 are you seeing this? https://travis-ci.org/stephengroat/termux-packages/jobs/344120232#L2291

**Comment by Grimler91** [comment]
@stephengroat hm, it built fine on my computer. Have to investigate that a bit.

**Comment by Grimler91** [comment]
Could perhaps be because your branch is so far behind master? 
I tried building again and it worked fine on the rebased branch (https://github.com/grimler91/termux-packages/tree/wireguard).

**Comment by stephengroat** [comment]
@Grimler91 still doesn't build. does the `WG_CONFIG_SEARCH_PATHS` need to be in `"` to signify string?

**Pull request closed without merging**
